// Build the backend, then node --test test/reports-pdf.test.cjs.
// Uses real Chromium PDF generation and HTTP transport, without real database writes.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { Test } = require('@nestjs/testing');
const { ValidationPipe, NotFoundException } = require('@nestjs/common');
const { ReportsController } = require('../dist/src/reports/reports.controller');
const { ReportsService } = require('../dist/src/reports/reports.service');

test('individual and course report endpoints deliver the original PDF bytes, not JSON', async () => {
  const renderer = new ReportsService({}, {}, {}, { get: () => undefined });
  const pdf = await renderer.renderPdf('<!doctype html><html><body><h1>Boletín de prueba</h1></body></html>');
  assert.equal(pdf.subarray(0, 5).toString(), '%PDF-');
  assert.match(pdf.subarray(-100).toString(), /%%EOF/);
  const calls = [];
  const generate = async (id, period) => {
    if (id === 'missing') throw new NotFoundException('Recurso no encontrado.');
    calls.push({ id, period });
    return pdf;
  };
  const module = await Test.createTestingModule({
    controllers: [ReportsController],
    providers: [{ provide: ReportsService, useValue: {
      generateStudentReportCard: generate, generateCourseReportCards: generate,
    } }],
  }).compile();
  const app = module.createNestApplication();
  app.setGlobalPrefix('api');
  app.useGlobalPipes(new ValidationPipe({ transform: true, whitelist: true, forbidNonWhitelisted: true }));
  try {
    await app.listen(0, '127.0.0.1');
    const origin = await app.getUrl();
    for (const [path, id, period, filename] of [
      ['/reports/students/student-a/report-card', 'student-a', 1, 'boletin-estudiante-student-a.pdf'],
      ['/reports/courses/course-a/report-cards', 'course-a', 4, 'boletines-curso-course-a.pdf'],
    ]) {
      const response = await fetch(`${origin}/api${path}?period=${period}`);
      assert.equal(response.status, 200);
      assert.match(response.headers.get('content-type'), /^application\/pdf/);
      assert.ok(response.headers.get('content-disposition').includes(filename));
      const downloaded = Buffer.from(await response.arrayBuffer());
      assert.equal(downloaded.subarray(0, 5).toString(), '%PDF-', 'The HTTP response must start with the PDF signature');
      assert.deepEqual(downloaded, pdf, 'Downloading must preserve every generated byte');
      assert.deepEqual(calls.at(-1), { id, period });
    }
    const missing = await fetch(`${origin}/api/reports/students/missing/report-card?period=1`);
    assert.equal(missing.status, 404);
    assert.match(missing.headers.get('content-type'), /application\/json/);
    assert.equal((await missing.json()).message, 'Recurso no encontrado.');
    const invalid = await fetch(`${origin}/api/reports/courses/course-a/report-cards?period=9`);
    assert.equal(invalid.status, 400);
    assert.equal(calls.length, 2);
  } finally { await app.close(); }
});
